# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'VKAPPSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKAPPSwiftUI
pod 'Alamofire', '~> 5.5'
pod 'RealmSwift', '~> 10.25.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'Kingfisher', '~> 7.0'

end
